/**
 * Created by janeluck on 17/9/6.
 */
require('fixed-data-table-2/dist/fixed-data-table.css')

// require('../base.less')
require('../base-new.less')
require('../button.less')
require('../form.less')
require('../billings.less')
// require('../table.less')
require('../table-new.less')
// require('../main.less')
// require('../common.less')
require('../login-new.less')
require('../tree.less')
// require('../list.less')
require('../modal.less')
require('./infor-coment.less')
require('./pay-list.less')
require('./left-content.less')
require('./right-content.less')
require('./goodsRefer.less')
require('./inputButtonPanel.less')
require('./alert.less')
require('../spinBar.less')
require('./portalMenu.less')
require('./voucherList.less')
require('./electronic.less')
require('./touch.less')
require('./electronicBalance.less')